### ISSUE TITLE
[Bug]:   The "--stats-overview" option does not exist.  

### ISSUE THREAD

**Issue by nezaboravi** [eighty9nine/filament-advanced-widgets#2]
### What happened?

Command provided on ReadMe file does not work.

### How to reproduce the bug

Install the repo as per readme.

Copy very next command from Readme:
`php artisan make:filament-advanced-widget AdvancedStatsOverviewWidget --stats-overview`
Observe the error in console.

### Package Version

 "eightynine/filament-advanced-widgets": "^3.0",

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

### Notes

<img width="726" alt="image" src="https://github.com/user-attachments/assets/d5d44bac-74bd-436d-9cd8-75c8353834f3">

**Comment by alphaolomi** [comment]
hey @nezaboravi 

the option is `--advanced-stats-overview`

the command should be 

```bash
php artisan make:filament-advanced-widget AdvancedStatsOverviewWidget --advanced-stats-overview
```

**Comment by eighty9nine** [comment]
Thanks for pointing this out, @nezaboravi @alphaolomi . I have updated the documentation!
