### ISSUE TITLE
[Bug]:   The "--stats-overview" option does not exist.  

### ISSUE THREAD

**Issue by nezaboravi** [eighty9nine/filament-advanced-widgets#3]
### What happened?

Command provided on ReadMe file does not work.

### How to reproduce the bug

Install the repo as per readme.

Copy very next command from Readme:
`php artisan make:filament-advanced-widget AdvancedStatsOverviewWidget --stats-overview`
Observe the error in console.

### Package Version

 "eightynine/filament-advanced-widgets": "^3.0",

### PHP Version

8.2

### Laravel Version

11

### Notes

<img width="726" alt="image" src="https://github.com/user-attachments/assets/d5d44bac-74bd-436d-9cd8-75c8353834f3">
<img width="647" alt="image" src="https://github.com/user-attachments/assets/740029fa-96b6-4887-901d-031af78d49a6">
Same is for charts....

**Comment by eighty9nine** [comment]
This was resolved, please refer to https://github.com/eighty9nine/filament-advanced-widgets/issues/2#issuecomment-2295349782.
